test:
	ahcbench input1.cs
	ahcbench input2.cs
	ahcbench input3.cs

test-rotor: 
	clix ahcbench input1.cs
	clix ahcbench input2.cs
	clix ahcbench input3.cs

clean:
	del /q input1.cs.ahd input1.cs.orig
	del /q input2.cs.ahd input2.cs.orig
	del /q input3.cs.ahd input3.cs.orig
