test:
	SharpSATbench input1.cnf
	SharpSATbench input2.cnf
	SharpSATbench input3.cnf

full-test:
	SharpSATbench input1.cnf
	SharpSATbench input2.cnf
	SharpSATbench input3.cnf
	SharpSATbench 4pipe_4_ooo.cnf	
	SharpSATbench 5pipe_4_ooo.cnf
	SharpSATbench 9vliw_bp_mc.cnf

test-rotor:
	clix SharpSATbench input1.cnf
	clix SharpSATbench input2.cnf
	clix SharpSATbench input3.cnf

full-test-rotor: 
	clix SharpSATbench input1.cnf
	clix SharpSATbench input2.cnf
	clix SharpSATbench input3.cnf
	clix SharpSATbench 4pipe_4_ooo.cnf	
	clix SharpSATbench 5pipe_4_ooo.cnf
	clix SharpSATbench 9vliw_bp_mc.cnf
